name: Run Gradle on push
on: push
jobs:
  gradle:
    strategy:
      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute 'tooling test app' build
        run: ./gradlew -b apps/tooling-test-app/build.gradle.kts clean build test

      - name: Publish 'tooling test app' Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "apps/tooling-test-app/build/test-results/**/*.xml"

